USE pi;

INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Soja', 120.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Milho', 64.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Arroz', 85.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Trigo', 70.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Cevada', 65.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Aveia', 48.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Centeio', 50.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Triticale', 52.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Sorgo', 58.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Feijão carioca', 310.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Feijão preto', 300.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Ervilha', 220.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Grão-de-bico', 260.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Lentilha', 240.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Amendoim', 220.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Girassol', 210.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Canola', 340.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Linhaça', 190.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Chia', 780.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Algodão (caroço)', 2200.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Café arábica', 1800.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Café conilon (robusta)', 950.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Cacau', 6500.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Soja óleo (industrial)', 130.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Milhete', 56.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Trigo integral', 72.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Batata-inglesa', 95.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Batata-doce', 60.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Cebola', 120.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Alho', 420.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Tomate', 140.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Pimentão', 220.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Berinjela', 110.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Milho milho verde (industria)', 85.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Mandioca (aipim/mandioca)', 48.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Inhame', 75.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Macaxeira (raiz)', 50.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Batata-baroa', 85.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Aipim industrial', 55.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Cana-de-açúcar (por tonelada)', 120.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Açúcar cristal (por saca)', 220.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Açúcar refinado (por saca)', 240.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Algodão fibra', 2400.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Cenoura', 95.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Beterraba', 88.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Abóbora', 52.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Milho silagem (por tonelada)', 150.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Feno/soja (forragem)', 180.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Leite (kg equival.)', 3.30);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Uva (para mesa)', 360.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Uva (vinho)', 320.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Maçã', 280.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Pera', 240.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Banana prata', 110.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Banana nanica', 120.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Mamão', 95.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Manga', 85.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Abacaxi', 70.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Maracujá', 190.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Açaí', 420.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Caju (castanha)', 950.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Castanha-do-pará (baru/amazonas)', 1200.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Coco (seca)', 280.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Azeitona', 900.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Laranja', 140.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Limão Tahiti', 160.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Limão Siciliano', 220.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Tangerina', 130.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Ameixa', 340.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Pêssego', 300.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Morango', 420.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Blueberry (mirtilo)', 1600.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Amora', 900.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Framboesa', 1200.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Melancia', 60.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Melão', 70.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Abacate', 160.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Oliva (azeite)', 1400.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Erva-mate', 260.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Chá (variedades)', 420.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Hortelã', 150.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Manjericão', 160.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Salsa', 90.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Coentro', 85.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Tomilho', 120.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Borracha (seringueira, por tonelada)', 9000.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Eucalipto (madeira m3)', 120.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Pinus (madeira m3)', 110.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Bambu (madeira)', 80.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Tomate para indústria', 95.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Marmelo', 230.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Pimenta-do-reino', 4200.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Pimenta malagueta', 320.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Gengibre', 480.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Cúrcuma (açafrão-da-terra)', 520.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Noz-pecã', 2400.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Noz comum (avelã)', 2200.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Macadâmia', 2800.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Cânhamo (fibra)', 1500.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Ervilhaca', 200.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Capim-elefante (forragem)', 60.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Sisal', 175.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Tâmara', 1100.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Alfarroba', 850.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Pinhão', 360.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Ervilha forrageira', 150.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Semente de trevo', 420.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Semente de alfafa', 380.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Fumo (tabaco)', 2000.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Remolacha (beterraba açucareira)', 68.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Espinafre', 95.00);
INSERT INTO `cultura`(`nome_cultura`, `valor_unitario`) VALUES ('Alface', 78.00);
